#!/bin/sh
set -e

# data/ is gitignored and regenerated by the build command. Rebuild it here only
# if it is missing, so cold starts don't re-download the Retraction Watch CSV.
if [ ! -f data/data.json ]; then
  echo "data/data.json missing — running data import..."
  uv run python import_xlsx.py FORRT_Lighthouse_Data.xlsx --retractions-csv data/retraction_watch.csv
fi

echo "Starting server..."
exec uv run gunicorn app:app --bind "0.0.0.0:${PORT:-10000}" --workers 2
